# CAN parameters
WIDTH = 400
HEIGHT = 320
PATCH_SIZE_PF = 8
NUM_FRAMES = 4
BE_CHANNELS = NUM_FRAMES * 512

# TimeSformer parameters
WIDTH_TS = WIDTH // PATCH_SIZE_PF
HEIGHT_TS = HEIGHT // PATCH_SIZE_PF
IN_CHANS = 512
PATCH_SIZE_TS = 2
DEPTH_TS = 2
NUM_HEADS = 8
EMBED_DIM = IN_CHANS * (PATCH_SIZE_TS * PATCH_SIZE_TS)
DIM_HEAD = EMBED_DIM // NUM_HEADS

MODEL_NAME = "400x320_1050_4f_fine_tuning_localized"
